# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_auto_20170512_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='slice',
            name='delay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.SliceDelay'),
            preserve_default=False,
        ),
    ]
