# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_slice_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='parent_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='slices',
        ),
        migrations.RemoveField(
            model_name='slice',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='slice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strategies.Slice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='offset_num',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Offset from Data point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='offset_type',
            field=models.CharField(choices=[('P', '%'), ('C', 'cents')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slice',
            name='reference_data_point',
            field=models.CharField(choices=[('BEST BID', 'BEST BID'), ('BEST OFFER', 'BEST OFFER'), ('LAST', 'LAST'), ('OPEN', 'OPEN'), ('DAILY HIGH', 'DAILY HIGH'), ('DAILY LOW', 'DAILY LOW'), ('DAILY NET PRICE', 'DAILY NET PRICE'), ('MTD NET PRICE', 'MTD NET PRICE'), ('NUMBER', 'NUMBER')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='bias_net',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Bias Net Position'),
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='num_slices',
            field=models.IntegerField(verbose_name='Number of Unique Slices'),
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parent Volume'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='delay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='strategies.SliceDelay', verbose_name='Slice Order Delay (Filled/Unfilled)'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='volume',
            field=models.IntegerField(verbose_name='Slice Order Volume'),
        ),
        migrations.AlterField(
            model_name='sliceprice',
            name='offset_num',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
