# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_auto_20171014_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='security',
            old_name='code',
            new_name='symbol',
        ),
    ]
