# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0006_auto_20171014_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slicedelay',
            old_name='filled',
            new_name='filled_lower',
        ),
        migrations.RenameField(
            model_name='slicedelay',
            old_name='unfilled',
            new_name='filled_upper',
        ),
        migrations.RemoveField(
            model_name='parentorder',
            name='security',
        ),
        migrations.AddField(
            model_name='parentorder',
            name='symbol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slicedelay',
            name='unfilled_lower',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slicedelay',
            name='unfilled_upper',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentorder',
            name='limit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Parent Limit Price'),
        ),
    ]
